### ISSUE TITLE
Calendar view immediately reopens if open and widget is clicked

### ISSUE THREAD

**Issue by Skrimpton** [MarcinOrlowski/html-clock-plasmoid#52] opened 2022-09-24 03:07 UTC
**What's wrong?**

Calendar view immediately reopens, if open and widget is clicked

------------------------------------------------------------

**Steps to reproduce the behavior:**

 1. Add widget to desktop
 2. Click widget
 3. Click widget again to close calendar view
 4. Fail and be very sad

------------------------------------------------------------

**Expected behavior**

I was hoping it would close the calendar view

------------------------------------------------------------

**Runtime environment**

 - HTML Clock version: 1.6.3, 1.6.2
 - Plasma version: 5.25.5
 - Name and version of OS: Manjaro 22.0.0 Sikaris
 - Qt version: 5.15.5
 - Laptop: Lenovo Legion y530 (maybe it's a touchpad issue)

------------------------------------------------------------

**Notes**

I'm not sure if the current behavior might be a me issue, Manjaro issue, or a widget issue.

Fixed it (I think, works with my preferences) by doing this in mainContainer in HtmlClock.qml:

```
	property bool wasExpanded: plasmoid.expanded

		MouseArea {
			id: mouseArea
			anchors.fill: parent
			onPressed: wasExpanded = plasmoid.expanded
			onClicked: {
				plasmoid.expanded = !wasExpanded
			}
		}

```

*COPYRIGHT DISCLAIMER:*
Concept is originally from some other plasmoid I don't remember the name of

------------------------------------------------------------

**Friendly PS.**

This is a really superb widget.
Sorry for nitpicking, and sorry if the suggested solution is bad or old news.

**Comment by MarcinOrlowski** [comment] 2023-02-20 17:20
I am unable to reproduce this problem. Using the same plasmashell 5.25.5 on Kubuntu 22.10 and the calendar opens for as expected (and stays open) me when plasmoid is either on the desktop or in panel. Are you still having this problem?

**Comment by Skrimpton** [comment] 2023-02-24 08:21
No, the problem is gone now. Thanks for the heads up!
Dunno what it was. Haven't reformatted since the bug, so something has fixed it.

it affected all my clickable "Compact- to FullRepresentation" widgets placed on the desktop.

Anyways, also thanks for the new update! Hope you have a nice day :)

**Comment by MarcinOrlowski** [comment] 2023-02-24 11:55
Closing the ticket then. It would not be much of surprise to see inconsistent behavior of plasma across distributions. Seen that in the past too. Anyway, feel free to reopen if that would bite again.

**Closed by MarcinOrlowski** 2023-02-24 11:55 UTC
Labels: bug
