### ISSUE TITLE
Button text is not visible in User Layout 

### ISSUE THREAD

**Issue by abimagnus** [MarcinOrlowski/html-clock-plasmoid#35] opened 2021-06-05 15:11 UTC
First of all thanks for this awesome plasmoid..love the customization options..kudos

**What's wrong?**
Button text is not visible in User Layout.

**Steps to reproduce the behavior:**
 1. Right click the plasmoid>configure html clock>click user-layout option

**Expected behavior**
Text should be visible in user layout option

**Runtime environment**
 - HTML Clock version - 1.5.0
 - Plasma version - 5.21.5
 - Name and version of OS - Solus 4.2
 - Latte-dock 0.9.91

**Notes**
I'm using Wayland btw, however the issue is in X11 also
![Screenshot_20210605_203349](https://user-images.githubusercontent.com/8939183/120896236-528a4f00-c63e-11eb-8cc3-e16f4a1911d7.png)

**Comment by MarcinOrlowski** [comment] 2021-06-07 11:30
I cannot reproduce this. I used fresh KDE Neon with same Plasma as yours and tried on latte-dock 0.9.12 (which seems to be newer than 0.9.91 for some reasons) and see no issues you report. Can you check if this problem occurs when you use regular Panel or HTML Clock is a desktop widget?

**Comment by Jesus-M** [comment] 2021-06-07 18:36
Same situation here. I don't see any button on the 'user layout' window.

```
Operating System: Slackware 14.2-current
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.8
OS Type: 64-bit
Graphics Platform: X11
```

**Comment by MarcinOrlowski** [comment] 2021-06-07 19:28
Interesting. @Jesus-M Can you check if HTML Clock fails for you in standard Panel too, or it's just Latte related?

I am also open to suggestions how to repro this. As i mentioned, I tried both latte 0.9.11 on Kubuntu 20.04 and with latest Neon. And it worked for me

**Comment by abimagnus** [comment] 2021-06-08 13:47
> I cannot reproduce this. I used fresh KDE Neon with same Plasma as yours and tried on latte-dock 0.9.12 (which seems to be newer than 0.9.91 for some reasons) and see no issues you report. Can you check if this problem occurs when you use regular Panel or HTML Clock is a desktop widget?

Interesting..however i tried both from default panel and desktop widget i cannot see the "button text" as well in this also !

**Comment by Jesus-M** [comment] 2021-06-08 14:55
> Interesting. @Jesus-M Can you check if HTML Clock fails for you in standard Panel too, or it's just Latte related?
> 
> I am also open to suggestions how to repro this. As i mentioned, I tried both latte 0.9.11 on Kubuntu 20.04 and with latest Neon. And it worked for me

Yup, I tried in every possible way, and saw the issue every time

**Comment by MarcinOrlowski** [comment] 2021-07-14 08:04
I am really struggling making this happen locally. What you should see there is this:

![x](https://user-images.githubusercontent.com/8041294/125586317-cda58053-f0f7-4d3d-aacf-0a305afde36e.png)

**Comment by GaganChandan** [comment] 2021-07-15 04:34
First of all, it's an amazing widget and I really love it. 

But I'm having the same issue. I think that until you can fix this problem, you could upload the HTML code for the in-built layouts so that those of us unable to clone the layouts can copy/paste the code.

**Comment by MarcinOrlowski** [comment] 2021-07-15 07:39
Sorry for the troubles with the widget. Unfortunately to reproduce the issue locally is not helping me nailing down the culprit. I will try again though.

As for editing: you can always tweak the HTML in the code with any text editor: the plasmoid should sit in `~/.local/share/plasma/plasmoids/com.marcinorlowski.htmlclock` and all you need to do is to edit `layouts.js` file (full path `~/.local/share/plasma/plasmoids/com.marcinorlowski.htmlclock/contents/js/layouts.js`). Once you done, restart your plasma (and probably latte, if you use it). You could also use https://github.com/MarcinOrlowski/plasmoid-tools while working on your layout.

**Comment by JosRodOrt** [comment] 2021-07-21 18:57
Hi, i think the problem is that it can't find the property 'mininumWidth':

![image](https://user-images.githubusercontent.com/87780211/126544301-ec7ac441-ebef-4ef8-a1ec-c758a833c672.png)

**Comment by MarcinOrlowski** [comment] 2021-12-09 19:46
Quick update: "Luckily" I am able to reproduce the issue so fix is comming

**Comment by Vactarian** [comment] 2022-04-20 05:49
I am having the same issue. This looks like it would be really great otherwise.

**Comment by TheoCGaming** [comment] 2022-08-08 06:25
> Quick update: "Luckily" I am able to reproduce the issue so fix is coming

fix *is* coming right?

**Comment by MarcinOrlowski** [comment] 2022-08-25 20:32
I am currently overloaded and cannot work on int. Will try to allocate some time next weekend and hopefuly address whatever is pending in this project as this one affects me too.

**Comment by MarcinOrlowski** [comment] 2022-09-02 08:01
v1.6.3 is finally out with the fix for this issue. Feel free to reopen if for any reason you are still affected.

**Closed by MarcinOrlowski** 2022-09-02 08:01 UTC
Labels: bug
